name: Auto update certificates

on:
  workflow_dispatch:
  watch:
    types: [started]
  repository_dispatch:
    types: "Update certificates"

env:
  ACME: /home/runner/.acme.sh/acme.sh
  VULTR_API_KEY: ${{ secrets.VULTR_API_KEY }}
  RCLONECONF: ${{ secrets.RCLONECONF }}

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install & Configure acme.sh & Rclone
        run: |
          curl  https://get.acme.sh | sh
          unzip *.zip
          sudo cp rclone*/rclone /usr/bin/rclone
          mkdir -p ~/.config/rclone
          base64 -di > ~/.config/rclone/rclone.conf <<< $RCLONECONF
      - name: Issue certificates
        run: |
          mkdir -p ./ssl
          $ACME --register-account -m q211798501@hotmail.com --server zerossl
          $ACME --issue --dns dns_vultr -d moesakura.cc -d *.moesakura.cc -k ec-256
      - name: Upload certificates
        run: |
          rclone copyto ~/.acme.sh/moesakura.cc_ecc/fullchain.cer gdpersonal:certificates/moesakura.cc.cer
          rclone copyto ~/.acme.sh/moesakura.cc_ecc/moesakura.cc.key gdpersonal:certificates/moesakura.cc.key
